version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dev-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: joboffer123
      POSTGRES_PASSWORD: joboffer123
      POSTGRES_DB: jobofferdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - jobnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@joboffer.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - jobnetwork

  job-offers-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-offers-api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DATABASE_URL: postgres://joboffer123:joboffer123@postgres:5432/jobofferdb
      JOB_CRAWLER_SCHEDULE: "*/5 * * * * *"
    networks:
      - jobnetwork
    restart: unless-stopped

volumes:
  pgdata:

networks:
  jobnetwork:
    driver: bridge
